/* tslint:disable */
/* eslint-disable */
/**
 * Catfe
 * Le Catfe API Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Errors
 */
export interface Errors {
    /**
     * 
     * @type {string}
     * @memberof Errors
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof Errors
     */
    'msg'?: string;
    /**
     * 
     * @type {number}
     * @memberof Errors
     */
    'code': number;
}

