/* tslint:disable */
/* eslint-disable */
/**
 * Catfe
 * Le Catfe API Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewMenuItem
 */
export interface NewMenuItem {
    /**
     * 
     * @type {string}
     * @memberof NewMenuItem
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof NewMenuItem
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewMenuItem
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewMenuItem
     */
    'image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewMenuItem
     */
    'id'?: string;
}

