/* tslint:disable */
/* eslint-disable */
/**
 * Catfe
 * Le Catfe API Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewCat
 */
export interface NewCat {
    /**
     * 
     * @type {string}
     * @memberof NewCat
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof NewCat
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewCat
     */
    'breed'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewCat
     */
    'pairing'?: NewCatPairingEnum;
    /**
     * 
     * @type {string}
     * @memberof NewCat
     */
    'id'?: string;
}

export const NewCatPairingEnum = {
    PumpkinSpiceLatte: 'Pumpkin Spice Latte',
    RoyalMilkTea: 'Royal Milk Tea',
    BubbleTea: 'Bubble Tea',
    SenchaTea: 'Sencha Tea',
    StraightBlackCoffee: 'Straight Black Coffee',
    ChocoCappuccino: 'Choco Cappuccino',
    DirtyChai: 'Dirty Chai'
} as const;

export type NewCatPairingEnum = typeof NewCatPairingEnum[keyof typeof NewCatPairingEnum];


