/* tslint:disable */
/* eslint-disable */
/**
 * Catfe
 * Le Catfe API Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewReview
 */
export interface NewReview {
    /**
     * 
     * @type {string}
     * @memberof NewReview
     */
    'author': string;
    /**
     * 
     * @type {number}
     * @memberof NewReview
     */
    'rating': NewReviewRatingEnum;
    /**
     * 
     * @type {string}
     * @memberof NewReview
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof NewReview
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewReview
     */
    'id'?: string;
}

export const NewReviewRatingEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;

export type NewReviewRatingEnum = typeof NewReviewRatingEnum[keyof typeof NewReviewRatingEnum];


