/* tslint:disable */
/* eslint-disable */
/**
 * Catfe
 * Le Catfe API Endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { MenuItem } from '../models';
/**
 * MenuItemApi - axios parameter creator
 * @export
 */
export const MenuItemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all Menu Items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMenuItems: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/menu_items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MenuItemApi - functional programming interface
 * @export
 */
export const MenuItemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MenuItemApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all Menu Items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMenuItems(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMenuItems(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MenuItemApi - factory interface
 * @export
 */
export const MenuItemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MenuItemApiFp(configuration)
    return {
        /**
         * Get all Menu Items
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMenuItems(options?: any): AxiosPromise<Array<MenuItem>> {
            return localVarFp.getAllMenuItems(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MenuItemApi - object-oriented interface
 * @export
 * @class MenuItemApi
 * @extends {BaseAPI}
 */
export class MenuItemApi extends BaseAPI {
    /**
     * Get all Menu Items
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MenuItemApi
     */
    public getAllMenuItems(options?: AxiosRequestConfig) {
        return MenuItemApiFp(this.configuration).getAllMenuItems(options).then((request) => request(this.axios, this.basePath));
    }
}
