openapi: 3.0.3
info:
  description: Le Catfe API Endpoints
  title: Catfe
  version: 1.0.0
servers:
- description: API URL
  url: http://{domain}:{port}{base_path}
  variables:
    base_path:
      default: /
      enum:
      - /
      - /api/v1
    domain:
      default: localhost
      enum:
      - localhost
    port:
      default: "7080"
      enum:
      - "7080"
tags:
- name: api
- name: menu_items
paths:
  /health:
    get:
      operationId: getHealth
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error
      x-eov-operation-handler: controllers/DefaultController
  /menu_items:
    get:
      description: Get all Menu Items
      operationId: getAllMenuItems
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/MenuItem'
                type: array
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error
      tags:
      - menu_item
      x-eov-operation-handler: controllers/MenuItemController
  /cats:
    get:
      description: Get all Cats
      operationId: getAllCats
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Cat'
                type: array
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error
      tags:
      - cat
      x-eov-operation-handler: controllers/CatController
  /cats/reviews:
    post:
      operationId: postCatReview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewReview'
        required: true
      responses:
        "201":
          description: Created
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error
      summary: Post review of a Cat
      tags:
      - cat
      x-eov-operation-handler: controllers/CatController
components:
  responses:
    Error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Error
  schemas:
    Errors:
      example:
        msg: msg
        code: 0.8008281904610115
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        timestamp:
          format: date-time
          type: string
        msg:
          type: string
        code:
          type: number
      required:
      - code
      type: object
    NewMenuItem:
      discriminator:
        propertyName: classType
      properties:
        title:
          maxLength: 200
          type: string
          x-faker: commerce.productName
        description:
          type: string
          x-faker: lorem.paragraph
        price:
          type: string
          x-faker: commerce.price
        image_url:
          type: string
          x-faker:
            image.food:
            - 640
            - 480
            - food
            - true
        id:
          format: uuid
          type: string
          x-faker: datatype.uuid
      required:
      - title
      type: object
    MenuItem:
      allOf:
      - $ref: '#/components/schemas/NewMenuItem'
      required:
      - id
      - title
      type: object
    NewCat:
      discriminator:
        propertyName: classType
      properties:
        name:
          maxLength: 200
          type: string
          x-faker: name.firstName
        description:
          type: string
          x-faker: lorem.paragraph
        breed:
          type: string
          x-faker: animal.cat
        pairing:
          enum:
          - Pumpkin Spice Latte
          - Royal Milk Tea
          - Bubble Tea
          - Sencha Tea
          - Straight Black Coffee
          - Choco Cappuccino
          - Dirty Chai
          example: Choco Cappuccino
          type: string
        reviews:
          items:
            $ref: '#/components/schemas/Review'
          type: array
        rating:
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          example: 4
          type: number
        id:
          format: uuid
          type: string
          x-faker: datatype.uuid
      required:
      - name
      type: object
    Cat:
      allOf:
      - $ref: '#/components/schemas/NewCat'
      required:
      - id
      - name
      type: object
    NewReview:
      discriminator:
        propertyName: classType
      example:
        catId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        author: author
        rating: 4
        comment: comment
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: title
      properties:
        author:
          type: string
          x-faker: internet.userName
        rating:
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          example: 4
          type: number
        title:
          maxLength: 250
          type: string
          x-faker: company.catchPhrase
        comment:
          type: string
          x-faker: lorem.paragraph
        catId:
          format: uuid
          type: string
          x-faker: datatype.uuid
        id:
          format: uuid
          type: string
          x-faker: datatype.uuid
      required:
      - author
      - catId
      - rating
      - title
      type: object
    Review:
      allOf:
      - $ref: '#/components/schemas/NewReview'
      required:
      - author
      - id
      type: object
